site_name: Dclipse Documentation
site_url: https://msat1971.github.io/dclipse/
repo_url: https://github.com/msat1971/dclipse
repo_name: msat1971/dclipse
theme:
  name: material
  logo: assets/images/Logo_Brand_Dawg_Light.svg
  favicon: assets/images/favicon.png
  features:
    - navigation.sections
    - navigation.top
    - toc.follow
    - content.code.copy
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
  palette:
    - scheme: default
      primary: "#9ea1a1"
      accent: "#ba0c2f"
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: "#9ea1a1"
      accent: "#ba0c2f"
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
nav:
  - Home: index.md
  - Getting started:
      - Overview: getting-started/index.md
      - Installing: getting-started/installing.md
      - Configuring: getting-started/configuring.md
      - Troubleshooting: getting-started/troubleshooting.md
  - User Guide:
      - Overview: index.md
      - Schemas: schema/index.md
  - Integration:
      - Getting Started: integration/index.md
  - Project:
      - Codebase: project/index.md
  - Reference:
      - API Overview: reference/index.md
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/msat1971/dclipse
plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: true
            separate_signature: true
            merge_init_into_class: true
            inherited_members: true
            filters: ["!^_"]
extra_css:
  - assets/styles/extra.css
