name: CI

on:
  push:
    branches: [main, develop]
    tags:
      - 'v*'
  pull_request:
    branches: [main, develop]
  workflow_dispatch:
  release:
    types: [published]

jobs:
  test:
    name: Lint, type-check, and test with coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: "3.13"
          cache: pip

      - name: Install dev dependencies
        run: |
          python -m pip install -U pip
          pip install -e '.[dev]'
          pip install pre-commit

      - name: Run pre-commit (Ruff + docstring Examples policy)
        run: pre-commit run --all-files --show-diff-on-failure

      - name: Check schema sync (src -> schema, docs/schema)
        run: make schema-check

      - name: Type-check (mypy)
        run: mypy src/dclipse

      - name: Run tests with coverage
        run: |
          pytest --cov=src/dclipse --cov-branch --cov-report=xml

      - name: Upload results to Codecov
        uses: codecov/codecov-action@fdcc8476540edceab3de004e990f80d881c6cc00 # v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
