name: Docs

on:
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.13'

      - name: Install mkdocs
        run: |
          python -m pip install -U pip
          pip install mkdocs-material

      - name: Build site (verify only)
        run: |
          mkdocs build --strict --clean --site-dir ./_site
