name: Tests

on:
  push:
    branches: [main, develop]
    tags:
      - 'v*'
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.13'
          cache: pip

      - name: Install dev dependencies
        run: |
          python -m pip install -U pip
          pip install -e '.[dev]'

      - name: Run tests with coverage
        run: |
          pytest --cov=src/dclipse --cov-branch --cov-report=xml

      - name: Upload results to Codecov
        uses: codecov/codecov-action@fdcc8476540edceab3de004e990f80d881c6cc00 # v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
