name: Type

on:
  push:
    branches: [main, develop]
  pull_request:

permissions:
  contents: read

jobs:
  type:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.13'
          cache: pip

      - name: Install dev dependencies
        run: |
          python -m pip install -U pip
          pip install -e '.[dev]'

      - name: Mypy
        run: mypy src/dclipse
